//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inSyca.foundation.framework.application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inSyca.foundation.framework.application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationSource of WMI Events~Separate multiple sources with semicolon.
        /// </summary>
        public static string applicationsource {
            get {
                return ResourceManager.GetString("applicationsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap company {
            get {
                object obj = ResourceManager.GetObject("company", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the default user credentials should be used to access the SMTP mail server for SMTP transactions..
        /// </summary>
        public static string defaultcredentials {
            get {
                return ResourceManager.GetString("defaultcredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether SSL is used to access an SMTP mail server.~The default value is false..
        /// </summary>
        public static string enablessl {
            get {
                return ResourceManager.GetString("enablessl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglevel for Windows Eventlog~-1 = No Logging; 0 = Error only; 1 = Error and Warning only; 2 = Error, Warning and Information.
        /// </summary>
        public static string eventloglevel {
            get {
                return ResourceManager.GetString("eventloglevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Log Events~Separate multiple filter values with semicolon.
        /// </summary>
        public static string fulltextlogfilter {
            get {
                return ResourceManager.GetString("fulltextlogfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the hostname of the SMTP mail server to use for SMTP transactions.
        /// </summary>
        public static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string info_build {
            get {
                return ResourceManager.GetString("info_build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Build.
        /// </summary>
        public static string info_clrbuild {
            get {
                return ResourceManager.GetString("info_clrbuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Revision.
        /// </summary>
        public static string info_clrrevision {
            get {
                return ResourceManager.GetString("info_clrrevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Version.
        /// </summary>
        public static string info_clrversion {
            get {
                return ResourceManager.GetString("info_clrversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computername.
        /// </summary>
        public static string info_computername {
            get {
                return ResourceManager.GetString("info_computername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connection.
        /// </summary>
        public static string info_connection {
            get {
                return ResourceManager.GetString("info_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string info_culture {
            get {
                return ResourceManager.GetString("info_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string info_domain {
            get {
                return ResourceManager.GetString("info_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework.
        /// </summary>
        public static string info_dotnet_caption {
            get {
                return ResourceManager.GetString("info_dotnet_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string info_hostname {
            get {
                return ResourceManager.GetString("info_hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP V4 address.
        /// </summary>
        public static string info_ipv4 {
            get {
                return ResourceManager.GetString("info_ipv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP V6 address.
        /// </summary>
        public static string info_ipv6 {
            get {
                return ResourceManager.GetString("info_ipv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is64Bit.
        /// </summary>
        public static string info_is64 {
            get {
                return ResourceManager.GetString("info_is64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string info_memory_caption {
            get {
                return ResourceManager.GetString("info_memory_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetBIOS-Name.
        /// </summary>
        public static string info_netbios {
            get {
                return ResourceManager.GetString("info_netbios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string info_network_caption {
            get {
                return ResourceManager.GetString("info_network_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string info_os {
            get {
                return ResourceManager.GetString("info_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string info_os_caption {
            get {
                return ResourceManager.GetString("info_os_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string info_revision {
            get {
                return ResourceManager.GetString("info_revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string info_sys_caption {
            get {
                return ResourceManager.GetString("info_sys_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICulture.
        /// </summary>
        public static string info_uiculture {
            get {
                return ResourceManager.GetString("info_uiculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string info_user {
            get {
                return ResourceManager.GetString("info_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string info_version {
            get {
                return ResourceManager.GetString("info_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Set.
        /// </summary>
        public static string info_workingset {
            get {
                return ResourceManager.GetString("info_workingset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers to log WMI Events~Separate multiple servers with semicolon.
        /// </summary>
        public static string logservernames {
            get {
                return ResourceManager.GetString("logservernames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Configuration.
        /// </summary>
        public static string mb_caption {
            get {
                return ResourceManager.GetString("mb_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the configuration file. Reason( File &apos;{0}&apos; does not exist ).
        /// </summary>
        public static string mb_error_1 {
            get {
                return ResourceManager.GetString("mb_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the configuration file. Reason(&apos;{0}&apos;).
        /// </summary>
        public static string mb_error_2 {
            get {
                return ResourceManager.GetString("mb_error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save configuration. Reason(&apos;{0}&apos;).
        /// </summary>
        public static string mb_error_save {
            get {
                return ResourceManager.GetString("mb_error_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Application Configuration changes before closing?.
        /// </summary>
        public static string mb_save {
            get {
                return ResourceManager.GetString("mb_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Configuration changes have been saved..
        /// </summary>
        public static string mb_saved {
            get {
                return ResourceManager.GetString("mb_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the password to use for authentication to the SMTP mail server..
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the port number to use to connect to the SMTP mail server.~The default value is 25..
        /// </summary>
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemSource of WMI Events~Separate multiple sources with semicolon.
        /// </summary>
        public static string systemsource {
            get {
                return ResourceManager.GetString("systemsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_information.
        /// </summary>
        public static string tab_information_name {
            get {
                return ResourceManager.GetString("tab_information_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string tab_information_text {
            get {
                return ResourceManager.GetString("tab_information_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_logging.
        /// </summary>
        public static string tab_logging_name {
            get {
                return ResourceManager.GetString("tab_logging_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string tab_logging_text {
            get {
                return ResourceManager.GetString("tab_logging_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_monitoring.
        /// </summary>
        public static string tab_monitoring_name {
            get {
                return ResourceManager.GetString("tab_monitoring_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string tab_monitoring_text {
            get {
                return ResourceManager.GetString("tab_monitoring_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_smtp.
        /// </summary>
        public static string tab_smtp_name {
            get {
                return ResourceManager.GetString("tab_smtp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        public static string tab_smtp_text {
            get {
                return ResourceManager.GetString("tab_smtp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab_test.
        /// </summary>
        public static string tab_test_name {
            get {
                return ResourceManager.GetString("tab_test_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string tab_test_text {
            get {
                return ResourceManager.GetString("tab_test_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert tab page.
        /// </summary>
        public static string ts_insert {
            get {
                return ResourceManager.GetString("ts_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the user name to use for authentication to the SMTP mail server.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
