namespace inSyca.foundation.integration.biztalk.components
{
    using System;
    using System.IO;
    using System.Text;
    using Microsoft.BizTalk.Message.Interop;
    using Microsoft.BizTalk.Component.Interop;
    using Microsoft.BizTalk.Component;
    using System.Runtime.InteropServices;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using diagnostics;
    using System.ComponentModel;

    [ComponentCategory(CategoryTypes.CATID_PipelineComponent)]
    [ComponentCategory(CategoryTypes.CATID_DisassemblingParser)]
    [Guid("A2EC54AB-C269-44F1-891C-97C32B93F041")]
    public class FFRegEx : FFDasmComp, IBaseComponent, IComponentUI, IDisassemblerComponent, IPersistPropertyBag
    {
        private string regExReplacement = "\".*?\"";
        private bool removeEmptyLines = true;

        [Browsable(true)]
        public string RegExReplacement
        {
            get { return regExReplacement; }
            set { regExReplacement = value; }
        }

        [Browsable(true)]
        public bool RemoveEmptyLines
        {
            get { return removeEmptyLines; }
            set { removeEmptyLines = value; }
        }


        #region IBaseComponent Members
        /// <summary>
        /// Gets Description of the component
        /// </summary>   
        [Browsable(false)]
        public new string Description
        {
            get
            {
                return "FlatFile RegEx";
            }
        }

        /// <summary>
        /// Gets Name of the component
        /// </summary>   
        [Browsable(false)]
        public new string Name
        {
            get
            {
                return "FFRegEx";
            }
        }

        /// <summary>
        /// Gets Version of the component
        /// </summary>
        [Browsable(false)]
        public new string Version
        {
            get
            {
                return "1.0";
            }
        }
        #endregion

        #region IPersistPropertyBag

        /// <summary>
        /// Gets class ID of component for usage from unmanaged code.
        /// </summary>
        /// <param name="classid">Class ID of the component.</param>
        public new void GetClassID(out Guid classid)
        {
            Log.DebugFormat("GetClassID(out Guid classid)");

            classid = new System.Guid("A2EC54AB-C269-44F1-891C-97C32B93F041");
        }

        /// <summary>
        /// Not implemented.
        /// </summary>
        public new void InitNew()
        {
        }

        public new void Load(IPropertyBag propertyBag, int errorLog)
        {
            Log.DebugFormat("Load(IPropertyBag propertyBag {0} , int errorLog {1})", propertyBag, errorLog);

            base.Load(propertyBag, errorLog);

            using (DisposableObjectWrapper wrapper = new DisposableObjectWrapper(propertyBag))
            {
                object val = null;

                val = PropertyHelper.ReadPropertyBag(propertyBag, "RegExReplacement");
                if (val != null)
                    regExReplacement = (string)val;

                val = PropertyHelper.ReadPropertyBag(propertyBag, "RemoveEmptyLines");
                if (val != null)
                    removeEmptyLines = (bool)val;
            }

            Log.DebugFormat("Load RegExReplacement {0}", regExReplacement);
            Log.DebugFormat("Load RemoveEmptyLines {0}", removeEmptyLines);
        }

        public new void Save(IPropertyBag propertyBag, bool clearDirty, bool saveAllProperties)
        {
            Log.DebugFormat("Load(IPropertyBag propertyBag {0}, bool clearDirty {1}, bool saveAllProperties {2})", propertyBag, clearDirty, saveAllProperties);

            base.Save(propertyBag, clearDirty, saveAllProperties);

            using (DisposableObjectWrapper wrapper = new DisposableObjectWrapper(propertyBag))
            {
                object val = null;

                val = regExReplacement;
                propertyBag.Write("RegExReplacement", ref val);

                val = removeEmptyLines;
                propertyBag.Write("RemoveEmptyLines", ref val);
            }

            Log.DebugFormat("Save RegExReplacement {0}", regExReplacement);
            Log.DebugFormat("Save RemoveEmptyLines {0}", removeEmptyLines);
        }

        #endregion

        #region IComponentUI members
        /// <summary>
        /// Component icon to use in BizTalk Editor
        /// </summary>      
        public new IntPtr Icon
        {
            get
            {
                return Properties.Resources.cog.Handle;
            }
        }

        #endregion

        /// <summary>
        /// this variable will contain any message generated by the Disassemble method
        /// </summary>
        private System.Collections.Queue _msgs = new System.Collections.Queue();

        #region IDisassemblerComponent members

        /// <summary>
        /// Returns messages resulting from the disassemble method execution
        /// </summary>
        /// <param name="pipelineContext">the pipeline context</param>
        /// <returns></returns>
        public new IBaseMessage GetNext(IPipelineContext pipelineContext)
        {
            Log.DebugFormat("GetNext(IPipelineContext pc {0})", pipelineContext);
            // get the next message from the Queue and return it
            IBaseMessage msg = null;
            if (_msgs.Count > 0)
            {
                Log.DebugFormat("_msgs.Count {0}", _msgs.Count);

                msg = ((IBaseMessage)(_msgs.Dequeue()));

                return msg;
            }
            else
            {
                Log.DebugFormat("Queue empty");
                return msg;
            }
        }

        /// <summary>
        /// called by the messaging engine when a new message arrives
        /// </summary>
        /// <param name="pipelineContext">the pipeline context</param>
        /// <param name="inMsg">the actual message</param>
        public new void Disassemble(Microsoft.BizTalk.Component.Interop.IPipelineContext pipelineContext, Microsoft.BizTalk.Message.Interop.IBaseMessage inMsg)
        {
            Log.DebugFormat("Execute(IPipelineContext pContext {0}, IBaseMessage pInMsg {1})", pipelineContext, inMsg);

            IBaseMessagePart bodyPart = inMsg.BodyPart;

            if (bodyPart != null)
            {
                Stream originalStream = bodyPart.GetOriginalDataStream();

                if (originalStream != null)
                {
                    StreamReader sr = new StreamReader(originalStream);
                    string messageString = sr.ReadToEnd();
                    Log.DebugFormat("messageString before processing{0}", messageString);

                    if (removeEmptyLines)
                    {
                        Log.DebugFormat("removeEmptyLines {0}", removeEmptyLines);

                        messageString = messageString.TrimEnd('\r', '\n');
                        messageString = messageString + Environment.NewLine;
                    }

                    if (!string.IsNullOrEmpty(regExReplacement))
                    {
                        Log.DebugFormat("regExReplacement {0}", regExReplacement);

                        try
                        {
                            Regex rgx = new Regex(RegExReplacement);
                            messageString = rgx.Replace(messageString, "");
                        }
                        catch (Exception ex)
                        {
                            Log.Error("RegExReplacement Error {0}", ex);
                        }
                    }

                    Log.DebugFormat("messageString after processing{0}", messageString);
                    byte[] byteArray = Encoding.UTF8.GetBytes(messageString);
                    Stream ms = new MemoryStream(byteArray);

                    ms.Seek(0, SeekOrigin.Begin);

                    IBaseMessage outMsg;
                    outMsg = pipelineContext.GetMessageFactory().CreateMessage();
                    outMsg.AddPart("Body", pipelineContext.GetMessageFactory().CreateMessagePart(), true);
                    outMsg.BodyPart.Data = ms;

                    //Promote attachment file name
                    outMsg.Context = PipelineUtil.CloneMessageContext(inMsg.Context);

                    base.Disassemble(pipelineContext, outMsg);

                    _msgs.Enqueue(base.GetNext(pipelineContext));

                    Log.DebugFormat("Flatfile Dissasembler(IPipelineContext pContext {0}, IBaseMessage outMsg {1})", pipelineContext, outMsg);
                }
            }
        }
        #endregion
    }
}
