//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inSyca.foundation.framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inSyca.foundation.framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xml:lang=&apos;de-de&apos;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;EventLog Mail Template&lt;/title&gt;
        ///    &lt;style type=&apos;text/css&apos;&gt;
        ///        .header
        ///        {
        ///            width: 100%;
        ///            font-size: x-small;
        ///            height: 17px;
        ///            font-weight:bolder;
        ///        }
        ///
        ///        .signature
        ///        {
        ///            font-size: xx-small;
        ///        }
        ///
        ///        .disclaimer
        ///        {
        ///            font-size: xx-small;
        ///            color: #666666; 
        ///        }
        ///
        ///        .rowname
        ///        {
        ///            background-color: # [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventLog {
            get {
                return ResourceManager.GetString("EventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xml:lang=&apos;de-de&apos;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Filesystem Operation Mail Template&lt;/title&gt;
        ///    &lt;style type=&apos;text/css&apos;&gt;
        ///        .header
        ///        {
        ///            width: 100%;
        ///            font-size: x-small;
        ///            height: 17px;
        ///            font-weight: bolder;
        ///        }
        ///        
        ///        .signature
        ///        {
        ///            font-size: xx-small;
        ///        }
        ///        
        ///        .disclaimer
        ///        {
        ///            font-size: xx-small;
        ///            color: #666666;
        ///        }
        ///        
        ///        .rowname
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
    }
}
