//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inSyca.foundation.integration.biztalk.components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inSyca.foundation.integration.biztalk.components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - ActiveX Message Reader Component for BizTalk Piepelines.
        /// </summary>
        internal static string activeXMessageReader_description {
            get {
                return ResourceManager.GetString("activeXMessageReader_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveX Message Reader.
        /// </summary>
        internal static string activeXMessageReader_name {
            get {
                return ResourceManager.GetString("activeXMessageReader_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string activeXMessageReader_version {
            get {
                return ResourceManager.GetString("activeXMessageReader_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to append at the end of message.
        /// </summary>
        internal static string DescrAppendData {
            get {
                return ResourceManager.GetString("DescrAppendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to prepend at the beginning of message.
        /// </summary>
        internal static string DescrPrependData {
            get {
                return ResourceManager.GetString("DescrPrependData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to append is too long. Length of the string must not exceed 64 characters..
        /// </summary>
        internal static string ErrorAppendDataTooLong {
            get {
                return ResourceManager.GetString("ErrorAppendDataTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsgStream.Flush is not supported..
        /// </summary>
        internal static string ErrorFlushNotSupported {
            get {
                return ResourceManager.GetString("ErrorFlushNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsgStream.Length is not supported..
        /// </summary>
        internal static string ErrorLengthNotSupported {
            get {
                return ResourceManager.GetString("ErrorLengthNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsgStream.Position.set is not supported..
        /// </summary>
        internal static string ErrorPosSetNotSupported {
            get {
                return ResourceManager.GetString("ErrorPosSetNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to prepend is too long. Length of the string must not exceed 64 characters..
        /// </summary>
        internal static string ErrorPrependDataTooLong {
            get {
                return ResourceManager.GetString("ErrorPrependDataTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsgStream.Seek is not supported..
        /// </summary>
        internal static string ErrorSeekNotSupported {
            get {
                return ResourceManager.GetString("ErrorSeekNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsgStream.SetLength is not supported..
        /// </summary>
        internal static string ErrorSetLengthNotSupported {
            get {
                return ResourceManager.GetString("ErrorSetLengthNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsgStream.Write is not supported..
        /// </summary>
        internal static string ErrorWriteNotSupported {
            get {
                return ResourceManager.GetString("ErrorWriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - Excel Decoding Component for BizTalk Piepelines.
        /// </summary>
        internal static string excelDecoder_description {
            get {
                return ResourceManager.GetString("excelDecoder_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Decoder.
        /// </summary>
        internal static string excelDecoder_name {
            get {
                return ResourceManager.GetString("excelDecoder_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string excelDecoder_version {
            get {
                return ResourceManager.GetString("excelDecoder_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - FF Xml Message Split Component for BizTalk Piepelines.
        /// </summary>
        internal static string ffXmlSplitter_description {
            get {
                return ResourceManager.GetString("ffXmlSplitter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF Xml Message Split.
        /// </summary>
        internal static string ffXmlSplitter_name {
            get {
                return ResourceManager.GetString("ffXmlSplitter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string ffXmlSplitter_version {
            get {
                return ResourceManager.GetString("ffXmlSplitter_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsg pipeline component.
        /// </summary>
        internal static string FixMsgDescription {
            get {
                return ResourceManager.GetString("FixMsgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMsg component.
        /// </summary>
        internal static string FixMsgName {
            get {
                return ResourceManager.GetString("FixMsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon inSyca {
            get {
                object obj = ResourceManager.GetObject("inSyca", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append data.
        /// </summary>
        internal static string PropAppendData {
            get {
                return ResourceManager.GetString("PropAppendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepend data.
        /// </summary>
        internal static string PropPrependData {
            get {
                return ResourceManager.GetString("PropPrependData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - Remove xsi:nil Elements  Component for BizTalk Piepelines.
        /// </summary>
        internal static string removeNil_description {
            get {
                return ResourceManager.GetString("removeNil_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Nil.
        /// </summary>
        internal static string removeNil_name {
            get {
                return ResourceManager.GetString("removeNil_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string removeNil_version {
            get {
                return ResourceManager.GetString("removeNil_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - Strip Messagebroker Body Component for BizTalk Piepelines.
        /// </summary>
        internal static string stripMessageBrokerBody_description {
            get {
                return ResourceManager.GetString("stripMessageBrokerBody_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strip Messagebroker Body.
        /// </summary>
        internal static string stripMessageBrokerBody_name {
            get {
                return ResourceManager.GetString("stripMessageBrokerBody_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string stripMessageBrokerBody_version {
            get {
                return ResourceManager.GetString("stripMessageBrokerBody_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - Substitute Characters and Strings Component for BizTalk Piepelines.
        /// </summary>
        internal static string substitute_description {
            get {
                return ResourceManager.GetString("substitute_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitute.
        /// </summary>
        internal static string substitute_name {
            get {
                return ResourceManager.GetString("substitute_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string substitute_version {
            get {
                return ResourceManager.GetString("substitute_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - UTF-16 Component for BizTalk Piepelines.
        /// </summary>
        internal static string UTF_16_description {
            get {
                return ResourceManager.GetString("UTF_16_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-16.
        /// </summary>
        internal static string UTF_16_name {
            get {
                return ResourceManager.GetString("UTF_16_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string UTF_16_version {
            get {
                return ResourceManager.GetString("UTF_16_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - UTF-8 Component for BizTalk Piepelines.
        /// </summary>
        internal static string UTF_8_description {
            get {
                return ResourceManager.GetString("UTF_8_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8.
        /// </summary>
        internal static string UTF_8_name {
            get {
                return ResourceManager.GetString("UTF_8_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string UTF_8_version {
            get {
                return ResourceManager.GetString("UTF_8_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - UTF-8 without BOM (Byte Order Mark) Component for BizTalk Piepelines.
        /// </summary>
        internal static string UTF_8_wo_BOM_description {
            get {
                return ResourceManager.GetString("UTF_8_wo_BOM_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8 without BOM (Byte Order Mark).
        /// </summary>
        internal static string UTF_8_wo_BOM_name {
            get {
                return ResourceManager.GetString("UTF_8_wo_BOM_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string UTF_8_wo_BOM_version {
            get {
                return ResourceManager.GetString("UTF_8_wo_BOM_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - Xml MultiPart Assembler Component for BizTalk Piepelines.
        /// </summary>
        internal static string xmlMultiPartAssembler_description {
            get {
                return ResourceManager.GetString("xmlMultiPartAssembler_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml MultiPart Assembler.
        /// </summary>
        internal static string xmlMultiPartAssembler_name {
            get {
                return ResourceManager.GetString("xmlMultiPartAssembler_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string xmlMultiPartAssembler_version {
            get {
                return ResourceManager.GetString("xmlMultiPartAssembler_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - Xml Message Split Component for BizTalk Piepelines.
        /// </summary>
        internal static string xmlSplitter_description {
            get {
                return ResourceManager.GetString("xmlSplitter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Message Split.
        /// </summary>
        internal static string xmlSplitter_name {
            get {
                return ResourceManager.GetString("xmlSplitter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string xmlSplitter_version {
            get {
                return ResourceManager.GetString("xmlSplitter_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSyca - Xsl Transformation Component for BizTalk Piepelines.
        /// </summary>
        internal static string xslTransformer_description {
            get {
                return ResourceManager.GetString("xslTransformer_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xsl Transformation.
        /// </summary>
        internal static string xslTransformer_name {
            get {
                return ResourceManager.GetString("xslTransformer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string xslTransformer_version {
            get {
                return ResourceManager.GetString("xslTransformer_version", resourceCulture);
            }
        }
    }
}
