//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inSyca.foundation.integration.biztalk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inSyca.foundation.integration.biztalk.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;de-de&quot;&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width: 100%; font-family: Arial, Helvetica, sans-serif; font-size: medium;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 100%; font-size: medium;&quot;&gt;
        ///                &lt;strong&gt;&lt;span style=&quot;color: #FF0000;&quot;&gt;Status&lt;/span&gt; BizTalk Host Instance&lt;/strong&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///                &lt;img alt=&quot;inSyca UG (haftungsbeschr&amp;auml;nkt)&quot; height=&quot;70&quot; src=&quot;http://www.inSyca.com/images/logo.png&quot; /&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HostInstance {
            get {
                return ResourceManager.GetString("HostInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;de-de&quot;&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width: 100%; font-family: Arial, Helvetica, sans-serif; font-size: medium;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 100%; font-size: medium;&quot;&gt;
        ///                &lt;strong&gt;&lt;span style=&quot;color: #FF0000;&quot;&gt;Status&lt;/span&gt; BizTalk Receive Location&lt;/strong&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///                &lt;img alt=&quot;inSyca UG (haftungsbeschränkt)&quot; height=&quot;70&quot; src=&quot;http://www.inSyca.com/images/logo.png&quot; /&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReceiveLocation {
            get {
                return ResourceManager.GetString("ReceiveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;de-de&quot;&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width: 100%; font-family: Arial, Helvetica, sans-serif; font-size: medium;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 100%; font-size: medium;&quot;&gt;
        ///                &lt;strong&gt;&lt;span style=&quot;color: #FF0000;&quot;&gt;Status&lt;/span&gt; BizTalk Send Port&lt;/strong&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///                &lt;img alt=&quot;inSyca UG (haftungsbeschränkt)&quot; height=&quot;70&quot; src=&quot;http://www.inSyca.com/images/logo.png&quot; /&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SendPort {
            get {
                return ResourceManager.GetString("SendPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;de-de&quot;&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width: 100%; font-family: Arial, Helvetica, sans-serif; font-size: medium;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 100%; font-size: medium;&quot;&gt;
        ///                &lt;strong&gt;&lt;span style=&quot;color: #FF0000;&quot;&gt;Suspended&lt;/span&gt; BizTalk Message&lt;/strong&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///                &lt;img alt=&quot;inSyca UG (haftungsbeschränkt)&quot; height=&quot;70&quot; src=&quot;http://www.inSyca.com/images/logo.png&quot; /&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SuspendedMessage {
            get {
                return ResourceManager.GetString("SuspendedMessage", resourceCulture);
            }
        }
    }
}
